repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-toml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: check-byte-order-marker
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: Sorting import statements
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-annotations==2.9.0
          - flake8-broken-line==0.4.0
          - flake8-bugbear==22.6.22
          - flake8-comprehensions==3.10.0
          - flake8-eradicate==1.2.1
          - flake8-no-pep420==2.3.0
          - flake8-todos==0.1.5
          - flake8-simplify==0.19.2
          - flake8-tidy-imports==4.8.0
          - flake8-use-fstring==1.3
          - flake8-docstrings==1.6.0
          - flake8-class-attributes-order==0.1.3
          - flake8-print==5.0.0
          - pep8-naming==0.13.0
          # - flake8-bandit
